<?php
 /* File: fields_login.inc
  * Desc: Contains arrays with the field names and form
  *       elements for the login Web page.
*/
$page = array( "title"  => "Admin Login Page",
               "top"    => "",
               "bottom" => "Send questions and comments
                            to admin@ourplace.com",
             );

$elements_1 = array( "top" => "Wel-Come to Kevin Carey Administrator Area 
                               <span style=\"font-size: 80%; 
                               font-weight: 100%\">
                               <i> - Login here</i></span>",
                     "bottom" => "",
                     "submit" => "Login"
                   );

$fields_1 =   array("fusername" => "User Name",
                    "fpassword" => "Password"
                   );
$length_1 =   array("fusername" => "10",
                    "fpassword" => "10"
                   );

?>
