<?php
$elements = array( "top" => "Contact Us 
                               <span style=\"font-size: 80%; 
                               font-weight: 100%\">
                               <i> - Form here</i></span>",
                     "bottom" => "",
                     "submit" => "Submit"
                   );
$types= array("clientname" => "text",
                    "email"=> "text",
					"cphone" => "text",
					"subject"=>"text",
					"message"=>"textarea"
					);
$fields =   array("clientname" => "Full Name:",
                    "email"=> "Email:",
					"cphone" => "Phone:",
					"subject"=>"Subject:",
					"message"=>"Mesage:"
					
                   );
$length =   array("clientname" => "55",
                    "email" => "55",
					"cphone"=>"15",
					"subject"=>"60"
                   );

?>